In [50]:
# ImageNet-1k Evaluation

            # Top-1 Accuracy
            # Top-5 Accuracy
            # Precision
            # Recall
            # F1-Score
            # Mean Average Precision (mAP)

In [16]:
from evaluate import load

metrics_ = load('trec_eval')
metrics_

EvaluationModule(name: "trec_eval", module_type: "metric", features: {'predictions': {'query': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'q0': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'docid': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'rank': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'score': Sequence(feature=Value(dtype='float32', id=None), length=-1, id=None), 'system': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None)}, 'references': {'query': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'q0': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'docid': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'rel': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None)}}, usage: """
Calculates TREC evaluation scores based on a run and qrel.
Args:
    predictions: list containing a single

In [4]:
####### Top-1 Accuracy

import numpy as np
import evaluate

accuracyk = evaluate.load("KevinSpaghetti/accuracyk")

predictions = np.array([
    [3],
    [4],
    [1],
])

references = np.array([3, 4, 0])

results = accuracyk.compute(predictions=predictions, references=references)
print(results)


{'accuracy': 0.6666666666666666}


In [5]:
####### Top-5 Accuracy


import numpy as np
import evaluate

accuracyk = evaluate.load("KevinSpaghetti/accuracyk")

predictions = np.array([
    [0, 7, 1, 3, 5],
    [0, 2, 9, 8, 4],
    [8, 4, 1, 2, 3],
])
references = np.array([3, 4, 0])

results = accuracyk.compute(predictions=predictions, references=references)
print(results)

{'accuracy': 0.6666666666666666}


In [49]:
#### get top 3 (say top 5) from full row of 5 elements (say 1000)

import numpy as np

predictions = np.array([
    [0.         , 0.30434783, 0.04347826, 0.13043478, 0.2173913 ],
    [0.         , 0.09090909, 0.40909091, 0.36363636, 0.18181818],
    [0.61538462, 0.30769231, 0.07692308, 0.07692308, 0.15384615]
])

# Get the indices of the top 3 maximum values in each row
top3_indices = np.argsort(-predictions, axis=1)[:, :3] # descending order


print(top3_indices)


[[1 4 3]
 [2 3 4]
 [0 1 4]]


In [39]:
####### Precision

import numpy as np
import evaluate

metric = evaluate.load("precision")

predictions = np.array([
    [0, 7, 1, 3, 5],
    [0, 2, 9, 8, 4],
    [8, 4, 1, 1, 3],
])
references = np.array([3, 4, 0])

results = metric.compute(predictions=predictions.argmax(axis=1), references=references,
                         pos_label=1, average=None, zero_division=1, labels = [0,1,2,3,4])
print(results)

labels = [0, 1, 2, 3, 4]

counts = [np.count_nonzero(references == label) for label in labels]

print(counts)

for i in labels:
    print(f"label {i}:\tprecision_accumulate = {results['precision'][i]* counts[i]}\tcount_accumulate = {counts[i]}")

for i in range(predictions.shape[0]):
    results = metric.compute(predictions=predictions[i:i+1, :].argmax(axis=1), references=references[i:i+1],
                            pos_label=1, average="weighted", zero_division=0, labels = [0,1,2,3,4])
    print(results)

{'precision': array([1., 0., 0., 1., 1.])}
[1, 0, 0, 1, 1]
label 0:	precision_accumulate = 1.0	count_accumulate = 1
label 1:	precision_accumulate = 0.0	count_accumulate = 0
label 2:	precision_accumulate = 0.0	count_accumulate = 0
label 3:	precision_accumulate = 1.0	count_accumulate = 1
label 4:	precision_accumulate = 1.0	count_accumulate = 1
{'precision': 0.0}
{'precision': 0.0}
{'precision': 1.0}


In [40]:
### COUNT

import numpy as np
import evaluate

metric = evaluate.load("precision")

predictions = np.array([3, 2, 0, 0])
references = np.array([3, 4, 0, 0])
labels = [0, 1, 2, 3, 4]

results = metric.compute(predictions=predictions, references=references,
                         pos_label=1, average=None, zero_division=1, labels = [0,1,2,3,4])
print(results)

labels = [0, 1, 2, 3, 4]

counts = [np.count_nonzero(references == label) for label in labels]

print(counts)

for i in labels:
    print(f"label {i}:\tprecision_accumulate = {results['precision'][i]* counts[i]}\tcount_accumulate = {counts[i]}")




{'precision': array([1., 1., 0., 1., 1.])}
[2, 0, 0, 1, 1]
label 0:	precision_accumulate = 2.0	count_accumulate = 2
label 1:	precision_accumulate = 0.0	count_accumulate = 0
label 2:	precision_accumulate = 0.0	count_accumulate = 0
label 3:	precision_accumulate = 1.0	count_accumulate = 1
label 4:	precision_accumulate = 1.0	count_accumulate = 1


In [41]:

####### Recall


import numpy as np
import evaluate

metric = evaluate.load("recall")

predictions = np.array([
    [0, 7, 1, 3, 5],
    [0, 2, 9, 8, 4],
    [8, 4, 1, 1, 3],
])
references = np.array([3, 4, 0])

results = metric.compute(predictions=predictions.argmax(axis=1), references=references,
                         pos_label=1, average=None, zero_division=1, labels = [0,1,2,3,4])
print(results)

labels = [0, 1, 2, 3, 4]

counts = [np.count_nonzero(references == label) for label in labels]

print(counts)

for i in labels:
    print(f"label {i}:\trecall_accumulate = {results['recall'][i]* counts[i]}\tcount_accumulate = {counts[i]}")

for i in range(predictions.shape[0]):
    results = metric.compute(predictions=predictions[i:i+1, :].argmax(axis=1), references=references[i:i+1],
                            pos_label=1, average="weighted", zero_division=0, labels = [0,1,2,3,4])
    print(results)


{'recall': array([1., 1., 1., 0., 0.])}
[1, 0, 0, 1, 1]
label 0:	recall_accumulate = 1.0	count_accumulate = 1
label 1:	recall_accumulate = 0.0	count_accumulate = 0
label 2:	recall_accumulate = 0.0	count_accumulate = 0
label 3:	recall_accumulate = 0.0	count_accumulate = 1
label 4:	recall_accumulate = 0.0	count_accumulate = 1
{'recall': 0.0}
{'recall': 0.0}
{'recall': 1.0}


In [45]:

####### F1-Score

import numpy as np
import evaluate

metric = evaluate.load("f1")

predictions = np.array([
    [0, 7, 1, 3, 5],
    [0, 2, 9, 8, 4],
    [8, 4, 1, 1, 3],
])
references = np.array([3, 4, 0])

results = metric.compute(predictions=predictions.argmax(axis=1), references=references,
                         pos_label=1, average=None, labels = [0,1,2,3,4])
print(results)

labels = [0, 1, 2, 3, 4]

counts = [np.count_nonzero(references == label) for label in labels]

print(counts)

for i in labels:
    print(f"label {i}:\tf1_accumulate = {results['f1'][i]* counts[i]}\tcount_accumulate = {counts[i]}")

for i in range(predictions.shape[0]):
    results = metric.compute(predictions=predictions[i:i+1, :].argmax(axis=1), references=references[i:i+1],
                            pos_label=1, average=None, labels = [0,1,2,3,4])
    print(results)


{'f1': array([1., 0., 0., 0., 0.])}
[1, 0, 0, 1, 1]
label 0:	f1_accumulate = 1.0	count_accumulate = 1
label 1:	f1_accumulate = 0.0	count_accumulate = 0
label 2:	f1_accumulate = 0.0	count_accumulate = 0
label 3:	f1_accumulate = 0.0	count_accumulate = 1
label 4:	f1_accumulate = 0.0	count_accumulate = 1


/media/toma/2TB_30May2023/OBJECT_DETECTION_L/object_detection/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1609: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))


{'f1': array([0., 0., 0., 0., 0.])}


/media/toma/2TB_30May2023/OBJECT_DETECTION_L/object_detection/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1609: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))


{'f1': array([0., 0., 0., 0., 0.])}
{'f1': array([1., 0., 0., 0., 0.])}


/media/toma/2TB_30May2023/OBJECT_DETECTION_L/object_detection/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1609: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))


In [41]:
from sklearn.metrics import average_precision_score
from transformers import EvalPrediction


def calculate_map(predictions, label_ids):

    # Get true labels
    labels = label_ids

    # Calculate average precision for each class
    average_precisions = []
    num_classes = predictions.shape[1]
    for class_idx in range(num_classes):

        print("class {}:".format(class_idx), average_precision_score(labels == class_idx, predictions[:, class_idx]))

        average_precisions.append(average_precision_score(labels == class_idx, predictions[:, class_idx]))

    # Calculate mean average precision (mAP)
    map_score = sum(average_precisions) / num_classes

    return map_score


predictions = np.array([
    [9, 4, 7, 8, 2, 0, 6, 5, 3, 1],
    [9, 1, 7, 8, 0, 3, 2, 5, 6, 4],
    [7, 0, 4, 8, 1, 6, 5, 2, 9, 3],
    [0, 5, 7, 4, 9, 3, 2, 1, 8, 6],
    [5, 9, 8, 2, 0, 7, 6, 3, 1, 4],
]) # say, predictions in float

# after argmax axis=1, result: [0 0 8 4 1]

# references = np.array([3, 4, 0, 2, 1])

references = np.array([0, 0, 8, 4, 1]) #(here, predictions == references)

results = calculate_map(predictions=predictions, label_ids=references)
print(results)


class 0: 1.0
class 1: 1.0
class 2: -0.0
class 3: -0.0
class 4: 1.0
class 5: -0.0
class 6: -0.0
class 7: -0.0
class 8: 1.0
class 9: -0.0
0.4


/media/toma/2TB_30May2023/OBJECT_DETECTION_L/object_detection/.venv/lib/python3.9/site-packages/sklearn/metrics/_ranking.py:891: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/media/toma/2TB_30May2023/OBJECT_DETECTION_L/object_detection/.venv/lib/python3.9/site-packages/sklearn/metrics/_ranking.py:891: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/media/toma/2TB_30May2023/OBJECT_DETECTION_L/object_detection/.venv/lib/python3.9/site-packages/sklearn/metrics/_ranking.py:891: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/media/toma/2TB_30May2023/OBJECT_DETECTION_L/object_detection/.venv/lib/python3.9/site-packages/sklearn/metrics/_ranking.py:891: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/media/toma/2TB_30May2023/OBJECT_DETECTION_L/object_detectio

In [ ]:
##### writing compute metrics function










In [ ]:
##### sample evaluation script with focalnet tiny model online available